### ISSUE TITLE
WASD moves at odd angles after lookat

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#151] opened 2015-07-14 14:08 UTC
Sometimes I find that if I do a lookat action, and then move, movement no longer moves straight ahead when I hit W.  Movement moves at an angle, sometimes only sightly off from forward, sometimes way off.

**Comment by grahamboree** [comment] 2015-07-14 14:56
Duplicate of #126

**Closed by grahamboree** 2015-07-14 14:56 UTC
Labels: bug, unity
