### ISSUE TITLE
Main Roleplay: AI cutting off scenario too early

### ISSUE THREAD

**Issue by tomaschko** [giantotter/giantotter_public#594] opened 2016-09-09 15:44 UTC
Most of the time, Olivia / Otto are quickly jumping to the end of the role play after my first or second comment

Ex1: 
- Olivia: "Whew, I'm glad that's over..."
- Me: "Yea. I know those are stressful\n Nice job though"
- Olivia: "Great! Thanks so much :heart:  It's so awesome to have supporters at work who have my back!"

Ex2: 
- Olivia: "Were you able to catch my presentation?"
- Me: "Um yes... I thought you told a good story \n But I did have a bit of feedback if you have a minute"
- Olivia: "Hm what do you mean? \n It wasn't too bad was it? \n I've had this issue ever since I can remember..." 
- Otto: "Alright that was a great effort..."

**Comment by jefforkin** [comment] 2016-09-09 19:02
v14 (removed label)

**Comment by jefforkin** [comment] 2016-09-15 04:14
Seen in v18:
- 2016-09-14 21:29:23  let's go immediately ends scenario.  also should blacklist mary's feedback intro
- 2016-09-14 17:28:56  scenario ends too early

**Comment by jefforkin** [comment] 2016-10-24 14:41
Aaron reported a bug where Otto moves onto the tutorial without asking for the users name.  I think this is caused by the same issue -- moving onto a new level 1 event before the first one is finished.

Aaron's log:
https://giantotter.github.io/webtools/#/logviewer/labels/aaron.otto.ai.v25.2.olivia/sessions/c18fcdf1-3406-4601-ba64-2e52b77e5b32?env=dev&_k=8n0efs

**Comment by jefforkin** [comment] 2016-10-24 21:35
I pushed a fix for this: c2c539066658e320871ad96a48cb3cad02f9d7ce

Confirmed that it fixes the bug Aaron reported.  Though may introduce some stalling in the main scenario, which will be resolved with level 1 aliasing.

**Closed as completed by jefforkin** 2016-10-24 21:35 UTC
Labels: bug, backend: AI, priority: A, Otto, OliviaBot
