### ISSUE TITLE
Remote sitting player moves while sitting

### ISSUE THREAD

**Issue by jefforkin** [giantotter/giantotter_public#135] opened 2015-07-09 03:43 UTC
I was the waitress.  Customer tried to stand up, and on my client his sitting body moved away from the table.  Meanwhile customer said to him it looked like an out of body experience, looking down from above.  Possibly same bug as #128

**Comment by jefforkin** [comment] 2015-07-09 03:48
Clark commented that he clicked Goto on the UI to try to stand up, and then had the out of body experience (as opposed to WASD to get up).

**Comment by tomaschko** [comment] 2015-07-09 15:09
I experienced something like this: when I try to stand up the camera rotates wildly - often settling briefly at about 90 degrees rotated, like my head is laying on its side - before returning to normal after I've fully stood up

**Comment by grahamboree** [comment] 2015-07-09 17:13
Could this be the same issue as #128?

**Comment by jefforkin** [comment] 2015-07-09 17:18
yes I think it it likely the exact same issue.  we could close one as duplicate.

**Comment by grahamboree** [comment] 2015-07-09 17:29
Duplicate of #128

**Closed by grahamboree** 2015-07-09 17:29 UTC
Labels: bug, TRG
